/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Base
 * @description The base element specifies the base URL to use for all relative URLs in a document. There can be at maximum one <base> element in a document, and it must be inside the <head> element.
 */



export default {
  title: "HTML5/Void Elements/Base",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The base element specifies the base URL to use for all relative URLs in a document. There can be at maximum one <base> element in a document, and it must be inside the <head> element.",
      },
    },
  },
  argTypes: {
    href: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    target: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies where to open the linked document.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "_blank", "_parent", "_self", "_top"],
    },
  },
  render: ({
    href,
    target,
  }) => {
    let el = document.createElement("base");
    if (href) {
      el.setAttribute('href', href);
    }
    if (target) {
      el.setAttribute('target', target);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    href: "Sample value",
    target: "",
  },
};
