/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Column
 * @description The col element represents a column in a table.
 */



export default {
  title: "HTML5/Void Elements/Column",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The col element represents a column in a table.",
      },
    },
  },
  argTypes: {
    span: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the number of columns the <col> element should span in a table.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    span,
    width,
    style,
  }) => {
    let el = document.createElement("col");
    if (span) {
      el.setAttribute('span', span);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    span: "Sample value",
    width: "Sample value",
    style: "Sample value",
  },
};
