/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Link
 * @description The link element defines a link between a document and an external resource. It is used to link to external stylesheets.
 */



export default {
  title: "HTML5/Void Elements/Link",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The link element defines a link between a document and an external resource. It is used to link to external stylesheets.",
      },
    },
  },
  argTypes: {
    crossorigin: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "anonymous", "use-credentials"],
    },
    href: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hreflang: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the language of the linked resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    integrity: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the integrity value of a resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    media: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type for which the linked resource or style sheet is intended.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    referrerpolicy: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the referrer policy for fetches initiated by the element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"],
    },
    rel: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the relationship between the current document and the linked document.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alternate", "author", "bookmark", "canonical", "help", "icon", "license", "manifest", "next", "nofollow", "noreferrer", "prefetch", "prev", "search", "stylesheet", "tag"],
    },
    sizes: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the sizes of the images or icons for different display/window sizes.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type of the linked resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    crossorigin,
    href,
    hreflang,
    integrity,
    media,
    referrerpolicy,
    rel,
    sizes,
    type,
    dir,
    hidden,
    lang,
    style,
    title,
  }) => {
    let el = document.createElement("link");
    if (crossorigin) {
      el.setAttribute('crossorigin', crossorigin);
    }
    if (href) {
      el.setAttribute('href', href);
    }
    if (hreflang) {
      el.setAttribute('hreflang', hreflang);
    }
    if (integrity) {
      el.setAttribute('integrity', integrity);
    }
    if (media) {
      el.setAttribute('media', media);
    }
    if (referrerpolicy) {
      el.setAttribute('referrerpolicy', referrerpolicy);
    }
    if (rel) {
      el.setAttribute('rel', rel);
    }
    if (sizes) {
      el.setAttribute('sizes', sizes);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    crossorigin: "",
    href: "Sample value",
    hreflang: "Sample value",
    integrity: "Sample value",
    media: "Sample value",
    referrerpolicy: "",
    rel: "",
    sizes: "Sample value",
    type: "Sample value",
    dir: "",
    hidden: false,
    lang: "Sample value",
    style: "Sample value",
    title: "Sample value",
  },
};
