/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Meta
 * @description The meta element provides metadata about the HTML document. Metadata will not be displayed on the page, but is machine-readable. Mainly used in the head but allowed inside the body if itemprop attribute is set.
 */



export default {
  title: "HTML5/Void Elements/Meta",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The meta element provides metadata about the HTML document. Metadata will not be displayed on the page, but is machine-readable. Mainly used in the head but allowed inside the body if itemprop attribute is set.",
      },
    },
  },
  argTypes: {
    charset: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the character encoding for the resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    content: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the http-equiv or name attribute.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    httpEquiv: {
      type: {
        name: "enum",
        required: false
      },
      description: "Provides an HTTP header for the information/value of the content attribute.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "content-language", "content-type", "default-style", "refresh"],
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    scheme: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the content type of the value attribute when the http-equiv attribute is used.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    charset,
    content,
    httpEquiv,
    name,
    scheme,
    hidden,
    lang,
    title,
  }) => {
    let el = document.createElement("meta");
    if (charset) {
      el.setAttribute('charset', charset);
    }
    if (content) {
      el.setAttribute('content', content);
    }
    if (httpEquiv) {
      el.setAttribute('http-equiv', httpEquiv);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (scheme) {
      el.setAttribute('scheme', scheme);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    charset: "Sample value",
    content: "Sample value",
    httpEquiv: "",
    name: "Sample value",
    scheme: "Sample value",
    hidden: false,
    lang: "Sample value",
    title: "Sample value",
  },
};
