/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Parameter
 * @description The param element defines parameters for an object element.
 */



export default {
  title: "HTML5/Void Elements/Parameter",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The param element defines parameters for an object element.",
      },
    },
  },
  argTypes: {
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    value: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the element. The meaning and usage may vary depending on the element type.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
  },
  render: ({
    name,
    value,
    style,
    hidden,
  }) => {
    let el = document.createElement("param");
    if (name) {
      el.setAttribute('name', name);
    }
    if (value) {
      el.setAttribute('value', value);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    name: "Sample value",
    value: "Sample value",
    style: "Sample value",
    hidden: false,
  },
};
