/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Script
 * @description The script element is used to embed or reference an executable script within an HTML document. Scripts without async or defer attributes, as well as inline scripts, are fetched and executed immediately, before the browser continues to parse the page.
 */



export default {
  title: "HTML5/Void Elements/Script",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The script element is used to embed or reference an executable script within an HTML document. Scripts without async or defer attributes, as well as inline scripts, are fetched and executed immediately, before the browser continues to parse the page.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    async: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the script will be executed asynchronously as soon as it is available.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    charset: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the character encoding for the resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    crossorigin: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "anonymous", "use-credentials"],
    },
    defer: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the script should be executed after the page has been parsed.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    integrity: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the integrity value of a resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    nonce: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a cryptographic nonce that can be used in Content Security Policy (CSP) checks.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    referrerpolicy: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the referrer policy for fetches initiated by the element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"],
    },
    src: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the media type of the linked resource.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "text/javascript", "module"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
    async,
    charset,
    crossorigin,
    defer,
    integrity,
    nonce,
    referrerpolicy,
    src,
    type,
    hidden,
    title,
    lang,
  }) => {
    let el = document.createElement("script");
    el.innerHTML = text;
    if (async) {
      el.setAttribute('async', async);
    }
    if (charset) {
      el.setAttribute('charset', charset);
    }
    if (crossorigin) {
      el.setAttribute('crossorigin', crossorigin);
    }
    if (defer) {
      el.setAttribute('defer', defer);
    }
    if (integrity) {
      el.setAttribute('integrity', integrity);
    }
    if (nonce) {
      el.setAttribute('nonce', nonce);
    }
    if (referrerpolicy) {
      el.setAttribute('referrerpolicy', referrerpolicy);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    async: false,
    charset: "Sample value",
    crossorigin: "",
    defer: false,
    integrity: "Sample value",
    nonce: "Sample value",
    referrerpolicy: "",
    src: "Sample value",
    type: "",
    hidden: false,
    title: "Sample value",
    lang: "Sample value",
  },
};
