/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Source
 * @description The source element allows authors to specify multiple media resources for media elements. It is an empty element. It is commonly used within the picture element.
 */



export default {
  title: "HTML5/Void Elements/Source",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The source element allows authors to specify multiple media resources for media elements. It is an empty element. It is commonly used within the picture element.",
      },
    },
  },
  argTypes: {
    media: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type for which the linked resource or style sheet is intended.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    sizes: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the sizes of the images or icons for different display/window sizes.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    src: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    srcset: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a list of possible image sources for the browser to use.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type of the linked resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
  },
  render: ({
    media,
    sizes,
    src,
    srcset,
    type,
    hidden,
  }) => {
    let el = document.createElement("source");
    if (media) {
      el.setAttribute('media', media);
    }
    if (sizes) {
      el.setAttribute('sizes', sizes);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (srcset) {
      el.setAttribute('srcset', srcset);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    media: "Sample value",
    sizes: "Sample value",
    src: "Sample value",
    srcset: "Sample value",
    type: "Sample value",
    hidden: false,
  },
};
