/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Style
 * @description The style element is used to embed CSS styles directly into an HTML document.
 */



export default {
  title: "HTML5/Void Elements/Style",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The style element is used to embed CSS styles directly into an HTML document.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    media: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type for which the linked resource or style sheet is intended.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    nonce: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a cryptographic nonce that can be used in Content Security Policy (CSP) checks.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies additional information about the element, typically displayed as a tooltip.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the media type of the inline styles.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "text/css"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
  },
  render: ({
    text,
    media,
    nonce,
    title,
    type,
    lang,
    dir,
  }) => {
    let el = document.createElement("style");
    el.innerHTML = text;
    if (media) {
      el.setAttribute('media', media);
    }
    if (nonce) {
      el.setAttribute('nonce', nonce);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    media: "Sample value",
    nonce: "Sample value",
    title: "Sample value",
    type: "",
    lang: "Sample value",
    dir: "",
  },
};
