/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Title
 * @description The title element defines the title of the document, shown in a browser's title bar or a page's tab. It is only text, not meant to be displayed.
 */



export default {
  title: "HTML5/Void Elements/Title",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The title element defines the title of the document, shown in a browser\'s title bar or a page\'s tab. It is only text, not meant to be displayed.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
  }) => {
    let el = document.createElement("title");
    el.innerHTML = text;

    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
  },
};
