/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Word Break Opportunity
 * @description The wbr element represents a word break opportunity.
 */



export default {
  title: "HTML5/Void Elements/Word Break Opportunity",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The wbr element represents a word break opportunity.",
      },
    },
  },
  argTypes: {
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
  },
  render: ({
    dir,
    hidden,
  }) => {
    let el = document.createElement("wbr");
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    dir: "",
    hidden: false,
  },
};
