/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Column Group
 * @description The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.
 */



export default {
  title: "HTML5/Block Elements/Column Group",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    span: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the number of columns the <col> element should span in a table.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
    span,
    dir,
    hidden,
    lang,
    style,
  }) => {
    let el = document.createElement("colgroup");
    el.innerHTML = text;
    if (span) {
      el.setAttribute('span', span);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    span: "Sample value",
    dir: "",
    hidden: false,
    lang: "Sample value",
    style: "Sample value",
  },
};
