/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Form
 * @description The form element represents a section of a document containing interactive controls for submitting information to a web server.
 */



export default {
  title: "HTML5/Block Elements/Form",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The form element represents a section of a document containing interactive controls for submitting information to a web server.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    acceptCharset: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the character encodings that are to be used for form submission.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    action: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the URL where the form data should be submitted when the form is submitted.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocomplete: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies whether a form or input field should have autocomplete enabled. Default is on.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    autocorrect: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    enctype: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies how form data should be encoded before sending it to a server. Only used if the method attribute is set to post. Default is application/x-www-form-urlencoded.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "application/x-www-form-urlencoded", "multipart/form-data", "text/plain"],
    },
    method: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "get", "post"],
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    novalidate: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that a form should not be validated when submitted.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    target: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies where to open the linked document.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "_blank", "_parent", "_self", "_top"],
    },
    ariaInvalid: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates that the value entered does not conform to the expected format.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "grammar", "spelling"],
    },
    ariaLabel: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "breadcrumb"],
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
  },
  render: ({
    text,
    acceptCharset,
    action,
    autocomplete,
    autocorrect,
    enctype,
    method,
    name,
    novalidate,
    target,
    ariaInvalid,
    ariaLabel,
    accesskey,
    dir,
    draggable,
    hidden,
    lang,
    style,
    tabindex,
    title,
    translate,
  }) => {
    let el = document.createElement("form");
    el.innerHTML = text;
    if (acceptCharset) {
      el.setAttribute('accept-charset', acceptCharset);
    }
    if (action) {
      el.setAttribute('action', action);
    }
    if (autocomplete) {
      el.setAttribute('autocomplete', autocomplete);
    }
    if (autocorrect) {
      el.setAttribute('autocorrect', autocorrect);
    }
    if (enctype) {
      el.setAttribute('enctype', enctype);
    }
    if (method) {
      el.setAttribute('method', method);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (novalidate) {
      el.setAttribute('novalidate', novalidate);
    }
    if (target) {
      el.setAttribute('target', target);
    }
    if (ariaInvalid) {
      el.setAttribute('aria-invalid', ariaInvalid);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    acceptCharset: "Sample value",
    action: "Sample value",
    autocomplete: "",
    autocorrect: "",
    enctype: "",
    method: "",
    name: "Sample value",
    novalidate: false,
    target: "",
    ariaInvalid: "",
    ariaLabel: "",
    accesskey: "Sample value",
    dir: "",
    draggable: false,
    hidden: false,
    lang: "Sample value",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
    translate: "",
  },
};
