/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Horizontal Rule
 * @description The hr element represents a thematic break between paragraph-level elements. It is typically a horizontal rule or line.
 */



export default {
  title: "HTML5/Block Elements/Horizontal Rule",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The hr element represents a thematic break between paragraph-level elements. It is typically a horizontal rule or line.",
      },
    },
  },
  argTypes: {
    align: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the horizontal alignment of the element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "center", "justify", "left", "right"],
    },
    color: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    noshade: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    size: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of a hr element in pixels.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    align,
    color,
    noshade,
    size,
    width,
    dir,
    hidden,
    lang,
    style,
    title,
  }) => {
    let el = document.createElement("hr");
    if (align) {
      el.setAttribute('align', align);
    }
    if (color) {
      el.setAttribute('color', color);
    }
    if (noshade) {
      el.setAttribute('noshade', noshade);
    }
    if (size) {
      el.setAttribute('size', size);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    align: "",
    color: "Sample value",
    noshade: false,
    size: "Sample value",
    width: "Sample value",
    dir: "",
    hidden: false,
    lang: "Sample value",
    style: "Sample value",
    title: "Sample value",
  },
};
