/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component HTML
 * @description The root element of an HTML document. It represents the top-level of the HTML structure.
 */



export default {
  title: "HTML5/Block Elements/HTML",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The root element of an HTML document. It represents the top-level of the HTML structure.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    manifest: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the address of the document\'s cache manifest.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
  },
  render: ({
    text,
    manifest,
    lang,
    dir,
  }) => {
    let el = document.createElement("html");
    el.innerHTML = text;
    if (manifest) {
      el.setAttribute('manifest', manifest);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    manifest: "Sample value",
    lang: "Sample value",
    dir: "",
  },
};
