/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Inline Frame
 * @description The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.
 */



export default {
  title: "HTML5/Block Elements/Inline Frame",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    allowfullscreen: {
      type: {
        name: "boolean",
        required: false
      },
      description: "Enables the iframe to be displayed in fullscreen mode.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    height: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    referrerpolicy: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the referrer policy for fetches initiated by the element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"],
    },
    sandbox: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    seamless: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the iframe should look like it is a part of the containing document (no borders or scrollbars).",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    src: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    srcdoc: {
      type: {
        name: "string",
        required: false
      },
      description: "The value of srcdoc is a string containing HTML markup, which the browser will display as the content of the iframe.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    role: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaBusy: {
      type: {
        name: "enum",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaHidden: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaLabel: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "breadcrumb"],
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
    allowfullscreen,
    height,
    name,
    referrerpolicy,
    sandbox,
    seamless,
    src,
    srcdoc,
    width,
    role,
    ariaControls,
    ariaDescribedby,
    ariaLabelledby,
    ariaBusy,
    ariaHidden,
    ariaLabel,
    dir,
    hidden,
    lang,
    style,
    tabindex,
    title,
  }) => {
    let el = document.createElement("iframe");
    el.innerHTML = text;
    if (allowfullscreen) {
      el.setAttribute('allowfullscreen', allowfullscreen);
    }
    if (height) {
      el.setAttribute('height', height);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (referrerpolicy) {
      el.setAttribute('referrerpolicy', referrerpolicy);
    }
    if (sandbox) {
      el.setAttribute('sandbox', sandbox);
    }
    if (seamless) {
      el.setAttribute('seamless', seamless);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (srcdoc) {
      el.setAttribute('srcdoc', srcdoc);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaBusy) {
      el.setAttribute('aria-busy', ariaBusy);
    }
    if (ariaHidden) {
      el.setAttribute('aria-hidden', ariaHidden);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    allowfullscreen: false,
    height: "Sample value",
    name: "Sample value",
    referrerpolicy: "",
    sandbox: "Sample value",
    seamless: false,
    src: "Sample value",
    srcdoc: "Sample value",
    width: "Sample value",
    role: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaLabelledby: "Sample value",
    ariaBusy: "",
    ariaHidden: "",
    ariaLabel: "",
    dir: "",
    hidden: false,
    lang: "Sample value",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
  },
};
