/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component NoScript
 * @description The noscript element defines an alternate content for users that have disabled scripts in their browser or have a browser that doesn't support script.
 */



export default {
  title: "HTML5/Block Elements/NoScript",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The noscript element defines an alternate content for users that have disabled scripts in their browser or have a browser that doesn\'t support script.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    contenteditable: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    inputmode: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
  },
  render: ({
    text,
    accesskey,
    autocapitalize,
    autofocus,
    contenteditable,
    dir,
    draggable,
    hidden,
    inputmode,
    lang,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
  }) => {
    let el = document.createElement("noscript");
    el.innerHTML = text;
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    autocapitalize: "",
    autofocus: false,
    contenteditable: "",
    dir: "",
    draggable: false,
    hidden: false,
    inputmode: "",
    lang: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
    translate: "",
  },
};
