/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Table Row
 * @description The tr element represents a row of cells in a table.
 */



export default {
  title: "HTML5/Block Elements/Table Row",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The tr element represents a row of cells in a table.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    align: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the horizontal alignment of each row cell. The possible enumerated values are left, center, right, justify, and char. When supported, the char value aligns the textual content on the character defined in the char attribute and on offset defined by the charoff attribute. Use the text-align CSS property instead, as this attribute is deprecated.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "left", "center", "right", "justify", "char"],
    },
    bgcolor: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the background color of each row cell. The value is an HTML color; either a 6-digit hexadecimal RGB code, prefixed by a #, or a color keyword. Other CSS <color> values are not supported. Use the background-color CSS property instead, as this attribute is deprecated.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    char: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the alignment of the content to a character of each row cell. Typical values for this include a period (.) when attempting to align numbers or monetary values. If align is not set to char, this attribute is ignored.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    charoff: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the number of characters to offset the row cell content from the alignment character specified by the char attribute.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    valign: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the vertical alignment of each row cell. The possible enumerated values are baseline, bottom, middle, and top. Use the vertical-align CSS property instead, as this attribute is deprecated.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "baseline", "bottom", "middle", "top"],
    },
    role: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaBusy: {
      type: {
        name: "enum",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaHidden: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    contenteditable: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    inputmode: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
  },
  render: ({
    text,
    align,
    bgcolor,
    char,
    charoff,
    valign,
    role,
    ariaControls,
    ariaDescribedby,
    ariaLabelledby,
    ariaBusy,
    ariaHidden,
    accesskey,
    autocapitalize,
    autofocus,
    contenteditable,
    dir,
    draggable,
    hidden,
    inputmode,
    lang,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
  }) => {
    let el = document.createElement("tr");
    el.innerHTML = text;
    if (align) {
      el.setAttribute('align', align);
    }
    if (bgcolor) {
      el.setAttribute('bgcolor', bgcolor);
    }
    if (char) {
      el.setAttribute('char', char);
    }
    if (charoff) {
      el.setAttribute('charoff', charoff);
    }
    if (valign) {
      el.setAttribute('valign', valign);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaBusy) {
      el.setAttribute('aria-busy', ariaBusy);
    }
    if (ariaHidden) {
      el.setAttribute('aria-hidden', ariaHidden);
    }
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    align: "",
    bgcolor: "Sample value",
    char: "Sample value",
    charoff: "Sample value",
    valign: "",
    role: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaLabelledby: "Sample value",
    ariaBusy: "",
    ariaHidden: "",
    accesskey: "Sample value",
    autocapitalize: "",
    autofocus: false,
    contenteditable: "",
    dir: "",
    draggable: false,
    hidden: false,
    inputmode: "",
    lang: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
    translate: "",
  },
};
