attributes:
  accesskey:
    description: "Specifies a shortcut key to activate or focus on the element."
    type: string
  class:
    description: "Specifies one or more class names for an element (refers to a class in a style sheet)."
    type: string
  contenteditable:
    description: "Specifies whether the content of an element is editable."
    type: boolean
  contextmenu:
    description: "Specifies a context menu for an element. The menu appears when a user right-clicks on the element."
    type: string
  dir:
    description: "Specifies the text direction for the content in an element. Possible values: 'ltr' (left-to-right), 'rtl' (right-to-left), 'auto'."
    type: ltr | rtl | auto
  draggable:
    description: "Specifies whether an element is draggable or not."
    type: boolean
  dropzone:
    description: "Specifies whether the dragged data can be copied, moved, or linked when dropped. Possible values: 'copy', 'move', 'link'."
    type: copy | move | link
  hidden:
    description: "Specifies whether an element is hidden or not. A hidden element is not displayed."
    type: boolean
  id:
    description: "Specifies a unique id for an element. Used to identify the element in a document."
    type: string
  lang:
    description: "Specifies the language of the element's content."
    type: string
  spellcheck:
    description: "Specifies whether the element should have its spelling and grammar checked or not."
    type: boolean
  style:
    description: "Specifies inline CSS styles for an element."
    type: string
  tabindex:
    description: "Specifies the tab order of an element. Used to determine the order in which elements receive focus when navigating with the 'Tab' key."
    type: integer
  title:
    description: "Specifies extra information about an element. Typically displayed as a tooltip when the mouse hovers over the element."
    type: string
  translate:
    description: "Specifies whether the content of an element should be translated or not."
    type: yes | no

event_attributes:
  onabort:
    description: "Event handler triggered when an element's loading is aborted."
    type: script
  onauxclick:
    description: "Event handler triggered when a pointing device button other than the primary one is clicked."
    type: script
  onblur:
    description: "Event handler triggered when an element loses focus."
    type: script
  oncancel:
    description: "Event handler triggered when an action is canceled."
    type: script
  oncanplay:
    description: "Event handler triggered when enough of the media resource has been downloaded to start playing."
    type: script
  oncanplaythrough:
    description: "Event handler triggered when the media can be played through to the end without buffering."
    type: script
  onchange:
    description: "Event handler triggered when the value of an element changes."
    type: script
  onclick:
    description: "Event handler triggered when an element is clicked."
    type: script
  onclose:
    description: "Event handler triggered when a user closes a document or view."
    type: script
  oncontextmenu:
    description: "Event handler triggered when a context menu is triggered."
    type: script
  oncuechange:
    description: "Event handler triggered when the cue changes in a <track> element."
    type: script
  ondblclick:
    description: "Event handler triggered when an element is double-clicked."
    type: script
  ondrag:
    description: "Event handler triggered when an element or text selection is being dragged."
    type: script
  ondragend:
    description: "Event handler triggered at the end of a drag operation."
    type: script
  ondragenter:
    description: "Event handler triggered when an element or text selection enters a valid drop target during a drag operation."
    type: script
  ondragexit:
    description: "Event handler triggered when an element or text selection exits a valid drop target during a drag operation."
    type: script
  ondragleave:
    description: "Event handler triggered when an element or text selection leaves a valid drop target during a drag operation."
    type: script
  ondragover:
    description: "Event handler triggered when an element or text selection is being dragged over a valid drop target."
    type: script
  ondragstart:
    description: "Event handler triggered at the start of a drag operation."
    type: script
  ondrop:
    description: "Event handler triggered when an element or text selection is dropped on a valid drop target."
    type: script
  ondurationchange:
    description: "Event handler triggered when the duration property of a media element changes."
    type: script
  onemptied:
    description: "Event handler triggered when a media element's readyState changes to 'empty'."
    type: script
  onended:
    description: "Event handler triggered when a media element has reached the end of playback."
    type: script
  onerror:
    description: "Event handler triggered when an error occurs during the loading of an element or a resource."
    type: script
  onfocus:
    description: "Event handler triggered when an element receives focus."
    type: script
  onformdata:
    description: "Event handler triggered when a FormData object is sent."
    type: script
  oninput:
    description: "Event handler triggered when the value of an element is changed by the user."
    type: script
  oninvalid:
    description: "Event handler triggered when an element is invalid."
    type: script
  onkeydown:
    description: "Event handler triggered when a key is pressed down."
    type: script
  onkeypress:
    description: "Event handler triggered when a key is pressed and released."
    type: script
  onkeyup:
    description: "Event handler triggered when a key is released."
    type: script
  onlanguagechange:
    description: "Event handler triggered when the user changes the document's language."
    type: script
  onload:
    description: "Event handler triggered when an element has finished loading."
    type: script
  onloadeddata:
    description: "Event handler triggered when the first frame of the media has finished loading."
    type: script
  onloadedmetadata:
    description: "Event handler triggered when metadata for the media has been loaded."
    type: script
  onloadstart:
    description: "Event handler triggered when the user agent begins looking for media data."
    type: script
  onmousedown:
    description: "Event handler triggered when a pointing device button is pressed down over an element."
    type: script
  onmouseenter:
    description: "Event handler triggered when a pointing device is moved onto an element."
    type: script
  onmouseleave:
    description: "Event handler triggered when a pointing device is moved away from an element."
    type: script
  onmousemove:
    description: "Event handler triggered when a pointing device is moved over an element."
    type: script
  onmouseout:
    description: "Event handler triggered when a pointing device is moved off an element."
    type: script
  onmouseover:
    description: "Event handler triggered when a pointing device is moved onto an element."
    type: script
  onmouseup:
    description: "Event handler triggered when a pointing device button is released."
    type: script
  onpause:
    description: "Event handler triggered when a media element is paused."
    type: script
  onplay:
    description: "Event handler triggered when a media element is ready to begin playback."
    type: script
  onplaying:
    description: "Event handler triggered when playback has started."
    type: script
  onprogress:
    description: "Event handler triggered while the user agent is fetching the media data."
    type: script
  onratechange:
    description: "Event handler triggered when the playback rate changes."
    type: script
  onreset:
    description: "Event handler triggered when a form is reset."
    type: script
  onresize:
    description: "Event handler triggered when the window or an element is resized."
    type: script
  onscroll:
    description: "Event handler triggered when an element's scrollbar is being scrolled."
    type: script
  onsecuritypolicyviolation:
    description: "Event handler triggered when a security policy is violated."
    type: script
  onseeked:
    description: "Event handler triggered when a media element has finished seeking."
    type: script
  onseeking:
    description: "Event handler triggered when a media element is seeking a new position."
    type: script
  onselect:
    description: "Event handler triggered when the user selects text in an element."
    type: script
  onslotchange:
    description: "Event handler triggered when the assigned nodes of a <slot> element changes."
    type: script
  onstalled:
    description: "Event handler triggered when a media element has stalled."
    type: script
  onsubmit:
    description: "Event handler triggered when a form is submitted."
    type: script
  onsuspend:
    description: "Event handler triggered when the loading of a media element is suspended."
    type: script
  ontimeupdate:
    description: "Event handler triggered when the playback position changes."
    type: script
  ontoggle:
    description: "Event handler triggered when the user opens or closes a <details> element."
    type: script
  onvolumechange:
    description: "Event handler triggered when the volume has changed."
    type: script
  onwaiting:
    description: "Event handler triggered when a media element is waiting for data."
    type: script
