a:
  attributes:
    class:
      description: 'The class attribute is used to define equal styles for multiple elements.'
      required: true
      defaultValue: ''
      type: enum
      choices:
        - ''
        - secondary
        - contrast
        - outline
        - secondary outline
        - contrast outline
    aria-current:
      description: 'The aria-current attribute is used to define the current item in a set of related elements.'
      type: enum
      defaultValue: ''
      choices:
        - ''
        - page
    role:
      description: 'The role attribute is used to define the purpose of an element.'
      type: enum
      defaultValue: ''
      choices:
        - ''
        - button