/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Button
 * @description The button element represents a clickable button, used to submit forms or anywhere in a document for accessible, standard button functionality.
 */



export default {
  title: "HTML5/Inline Elements/Button",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The button element represents a clickable button, used to submit forms or anywhere in a document for accessible, standard button functionality.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an element should automatically get focus when the page loads.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    autocorrect: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    disabled: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element should be disabled.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the type of the button.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "submit", "reset", "button"],
    },
    value: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the element. The meaning and usage may vary depending on the element type.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    role: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaCurrent: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates the current item within a container or set of related elements.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "page", "step", "location", "date", "time", "true"],
    },
    ariaBusy: {
      type: {
        name: "enum",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaLabel: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "breadcrumb"],
    },
    ariaDisabled: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    contenteditable: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    inputmode: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
  },
  render: ({
    text,
    autofocus,
    autocorrect,
    disabled,
    name,
    type,
    value,
    role,
    ariaControls,
    ariaDescribedby,
    ariaLabelledby,
    ariaCurrent,
    ariaBusy,
    ariaLabel,
    ariaDisabled,
    accesskey,
    autocapitalize,
    contenteditable,
    dir,
    draggable,
    hidden,
    inputmode,
    lang,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
  }) => {
    let el = document.createElement("button");
    el.innerHTML = text;
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (autocorrect) {
      el.setAttribute('autocorrect', autocorrect);
    }
    if (disabled) {
      el.setAttribute('disabled', disabled);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    if (value) {
      el.setAttribute('value', value);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaCurrent) {
      el.setAttribute('aria-current', ariaCurrent);
    }
    if (ariaBusy) {
      el.setAttribute('aria-busy', ariaBusy);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (ariaDisabled) {
      el.setAttribute('aria-disabled', ariaDisabled);
    }
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    autofocus: false,
    autocorrect: "",
    disabled: false,
    name: "Sample value",
    type: "",
    value: "Sample value",
    role: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaLabelledby: "Sample value",
    ariaCurrent: "",
    ariaBusy: "",
    ariaLabel: "",
    ariaDisabled: "",
    accesskey: "Sample value",
    autocapitalize: "",
    contenteditable: "",
    dir: "",
    draggable: false,
    hidden: false,
    inputmode: "",
    lang: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
    translate: "",
  },
};
