/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Image
 * @description The img element represents an image.
 */



export default {
  title: "HTML5/Inline Elements/Image",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The img element represents an image.",
      },
    },
  },
  argTypes: {
    alt: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies alternative text to be displayed when the image cannot be rendered.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    crossorigin: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "anonymous", "use-credentials"],
    },
    decoding: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the decoding process applied to the image.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "async", "auto", "sync"],
    },
    height: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ismap: {
      type: {
        name: "boolean",
        required: false
      },
      description: "Specifies that an area should be part of an image map.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    referrerpolicy: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the referrer policy for fetches initiated by the element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"],
    },
    sizes: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the sizes of the images or icons for different display/window sizes.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    src: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    srcset: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a set of image candidate URLs and descriptors for responsive images.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    usemap: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a client-side image map to be used with the element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaHidden: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaLabel: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "breadcrumb"],
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    alt,
    crossorigin,
    decoding,
    height,
    ismap,
    referrerpolicy,
    sizes,
    src,
    srcset,
    usemap,
    width,
    ariaHidden,
    ariaLabel,
    dir,
    draggable,
    hidden,
    lang,
    style,
    tabindex,
    title,
  }) => {
    let el = document.createElement("img");
    if (alt) {
      el.setAttribute('alt', alt);
    }
    if (crossorigin) {
      el.setAttribute('crossorigin', crossorigin);
    }
    if (decoding) {
      el.setAttribute('decoding', decoding);
    }
    if (height) {
      el.setAttribute('height', height);
    }
    if (ismap) {
      el.setAttribute('ismap', ismap);
    }
    if (referrerpolicy) {
      el.setAttribute('referrerpolicy', referrerpolicy);
    }
    if (sizes) {
      el.setAttribute('sizes', sizes);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (srcset) {
      el.setAttribute('srcset', srcset);
    }
    if (usemap) {
      el.setAttribute('usemap', usemap);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    if (ariaHidden) {
      el.setAttribute('aria-hidden', ariaHidden);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    alt: "Sample value",
    crossorigin: "",
    decoding: "",
    height: "Sample value",
    ismap: false,
    referrerpolicy: "",
    sizes: "Sample value",
    src: "Sample value",
    srcset: "Sample value",
    usemap: "Sample value",
    width: "Sample value",
    ariaHidden: "",
    ariaLabel: "",
    dir: "",
    draggable: false,
    hidden: false,
    lang: "Sample value",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
  },
};
