/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Input
 * @description The input element represents a typed data field, usually with a form control to allow user input.
 */



export default {
  title: "HTML5/Inline Elements/Input",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The input element represents a typed data field, usually with a form control to allow user input.",
      },
    },
  },
  argTypes: {
    accept: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a comma-separated list of file types that the server accepts.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocorrect: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    alt: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies alternative text to be displayed when the image cannot be rendered.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocomplete: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    checked: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it indicates that an input element should be pre-selected (checked) when the page loads.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    dirname: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the direction of the text.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    disabled: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element should be disabled.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    height: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    list: {
      type: {
        name: "string",
        required: false
      },
      description: "Refers to a <datalist> element that contains pre-defined options for an input element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    max: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the maximum value for an input element, meter, or progress element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    maxlength: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the maximum number of characters allowed in an input field.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    min: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the minimum value for an input element or a meter element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    minlength: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the minimum number of characters required in an input field.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    multiple: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the user is allowed to enter more than one value in an input element.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    pattern: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a regular expression that the <input> element\'s value is checked against.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    placeholder: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a short hint that describes the expected value of an input field.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    readonly: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element is read-only.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    required: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input field must be filled out before submitting the form.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    size: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of a hr element in pixels.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    src: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the URL of the external resource to be embedded or referenced. Required if input type is image",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    step: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the legal number intervals for an input element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies the type of the input. Defaults to text if the attribute is omitted",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "button", "checkbox", "color", "date", "datetime-local", "email", "file", "hidden", "image", "month", "number", "password", "radio", "range", "reset", "search", "submit", "tel", "text", "time", "url", "week"],
    },
    value: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the element. The meaning and usage may vary depending on the element type.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    role: {
      type: {
        name: "enum",
        required: false
      },
      description: "The role attribute is used to define the purpose of an element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaCurrent: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates the current item within a container or set of related elements.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "page", "step", "location", "date", "time", "true"],
    },
    ariaInvalid: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates that the value entered does not conform to the expected format.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "grammar", "spelling"],
    },
    ariaLabel: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "breadcrumb"],
    },
    ariaDisabled: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    contenteditable: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    inputmode: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
  },
  render: ({
    accept,
    autocorrect,
    alt,
    autocomplete,
    checked,
    dirname,
    disabled,
    height,
    list,
    max,
    maxlength,
    min,
    minlength,
    multiple,
    name,
    pattern,
    placeholder,
    readonly,
    required,
    size,
    src,
    step,
    type,
    value,
    width,
    role,
    ariaControls,
    ariaDescribedby,
    ariaLabelledby,
    ariaCurrent,
    ariaInvalid,
    ariaLabel,
    ariaDisabled,
    accesskey,
    autocapitalize,
    autofocus,
    contenteditable,
    dir,
    draggable,
    hidden,
    inputmode,
    lang,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
  }) => {
    let el = document.createElement("input");
    if (accept) {
      el.setAttribute('accept', accept);
    }
    if (autocorrect) {
      el.setAttribute('autocorrect', autocorrect);
    }
    if (alt) {
      el.setAttribute('alt', alt);
    }
    if (autocomplete) {
      el.setAttribute('autocomplete', autocomplete);
    }
    if (checked) {
      el.setAttribute('checked', checked);
    }
    if (dirname) {
      el.setAttribute('dirname', dirname);
    }
    if (disabled) {
      el.setAttribute('disabled', disabled);
    }
    if (height) {
      el.setAttribute('height', height);
    }
    if (list) {
      el.setAttribute('list', list);
    }
    if (max) {
      el.setAttribute('max', max);
    }
    if (maxlength) {
      el.setAttribute('maxlength', maxlength);
    }
    if (min) {
      el.setAttribute('min', min);
    }
    if (minlength) {
      el.setAttribute('minlength', minlength);
    }
    if (multiple) {
      el.setAttribute('multiple', multiple);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (pattern) {
      el.setAttribute('pattern', pattern);
    }
    if (placeholder) {
      el.setAttribute('placeholder', placeholder);
    }
    if (readonly) {
      el.setAttribute('readonly', readonly);
    }
    if (required) {
      el.setAttribute('required', required);
    }
    if (size) {
      el.setAttribute('size', size);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (step) {
      el.setAttribute('step', step);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    if (value) {
      el.setAttribute('value', value);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaCurrent) {
      el.setAttribute('aria-current', ariaCurrent);
    }
    if (ariaInvalid) {
      el.setAttribute('aria-invalid', ariaInvalid);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (ariaDisabled) {
      el.setAttribute('aria-disabled', ariaDisabled);
    }
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    accept: "Sample value",
    autocorrect: "",
    alt: "Sample value",
    autocomplete: "",
    checked: false,
    dirname: "Sample value",
    disabled: false,
    height: "Sample value",
    list: "Sample value",
    max: "Sample value",
    maxlength: "Sample value",
    min: "Sample value",
    minlength: "Sample value",
    multiple: false,
    name: "Sample value",
    pattern: "Sample value",
    placeholder: "Sample value",
    readonly: false,
    required: false,
    size: "Sample value",
    src: "Sample value",
    step: "Sample value",
    type: "",
    value: "Sample value",
    width: "Sample value",
    role: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaLabelledby: "Sample value",
    ariaCurrent: "",
    ariaInvalid: "",
    ariaLabel: "",
    ariaDisabled: "",
    accesskey: "Sample value",
    autocapitalize: "",
    autofocus: false,
    contenteditable: "",
    dir: "",
    draggable: false,
    hidden: false,
    inputmode: "",
    lang: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
    translate: "",
  },
};
