/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 2, 2025 00:53
 * @component Select
 * @description The select element represents a control for selecting amongst a set of options.
 */



export default {
  title: "HTML5/Inline Elements/Select",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The select element represents a control for selecting amongst a set of options.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    autocomplete: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    autocorrect: {
      type: {
        name: "enum",
        required: false
      },
      description: "Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    disabled: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element should be disabled.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    multiple: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the user is allowed to enter more than one value in an input element.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    required: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input field must be filled out before submitting the form.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    size: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of a hr element in pixels.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    role: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaInvalid: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates that the value entered does not conform to the expected format.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "grammar", "spelling"],
    },
    ariaLabel: {
      type: {
        name: "enum",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "breadcrumb"],
    },
    ariaDisabled: {
      type: {
        name: "enum",
        required: false
      },
      description: "Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    contenteditable: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    dir: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    inputmode: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "enum",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
  },
  render: ({
    text,
    autocomplete,
    autocorrect,
    disabled,
    multiple,
    name,
    required,
    size,
    role,
    ariaControls,
    ariaDescribedby,
    ariaLabelledby,
    ariaInvalid,
    ariaLabel,
    ariaDisabled,
    accesskey,
    autocapitalize,
    autofocus,
    contenteditable,
    dir,
    draggable,
    hidden,
    inputmode,
    lang,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
  }) => {
    let el = document.createElement("select");
    el.innerHTML = text;
    if (autocomplete) {
      el.setAttribute('autocomplete', autocomplete);
    }
    if (autocorrect) {
      el.setAttribute('autocorrect', autocorrect);
    }
    if (disabled) {
      el.setAttribute('disabled', disabled);
    }
    if (multiple) {
      el.setAttribute('multiple', multiple);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (required) {
      el.setAttribute('required', required);
    }
    if (size) {
      el.setAttribute('size', size);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaInvalid) {
      el.setAttribute('aria-invalid', ariaInvalid);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (ariaDisabled) {
      el.setAttribute('aria-disabled', ariaDisabled);
    }
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    autocomplete: "",
    autocorrect: "",
    disabled: false,
    multiple: false,
    name: "Sample value",
    required: false,
    size: "Sample value",
    role: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaLabelledby: "Sample value",
    ariaInvalid: "",
    ariaLabel: "",
    ariaDisabled: "",
    accesskey: "Sample value",
    autocapitalize: "",
    autofocus: false,
    contenteditable: "",
    dir: "",
    draggable: false,
    hidden: false,
    inputmode: "",
    lang: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: "Sample value",
    title: "Sample value",
    translate: "",
  },
};
