---
id: button
nodeValue: Button
nodeValueChoices:
  default: Button
  long: "Button with utf8 \U0001F436, <abbr title=\"Hypertext Markup Language\">html</abbr> and very <strong>long text</strong> and words <i>Antidisestablishmentarianism</i>"
nodeName: button
attributes:
- name: className
  control: select
  required: false
  choices:
    primary: ""
    secondary: secondary
    contrast: contrast
- name: type
  control: select
  required: false
  choices:
    button: button
    submit: submit
    reset: reset
- name: disabled
  control: boolean
  value: false
  required: true
...
