---
button:
  nodeName: button
  nodeValue: Button Text
  nodeValueChoices:
    default: Button Text
    # long: "Button with utf8 \U0001F436, <abbr title=\"Hypertext Markup Language\">html</abbr> and very <strong>long text</strong> and words <i>Antidisestablishmentarianism</i>"
  attributes:
  - name: class
    control: select
    required: false
    choices:
      primary: ""
      secondary: secondary
      contrast: contrast
  - name: type
    control: select
    required: false
    choices:
      button: button
      submit: submit
      reset: reset
  - name: disabled
    control: boolean
    value: false
    required: true
  - name: autofocus
    control: boolean
    value: false
    required: true
  ...